### ISSUE TITLE
Create page-specific social media card previews

### ISSUE THREAD

**Issue by ariel** [spacehackers/luti#115]
When linking to things like https://lifeundertheice.org/thanks - the Twitter/FB card should list the title of the page, and not just preview the generic home page title.

**Comment by mattb** [comment]
Can  you give an example of what the title and description should be for a specific microbe?

Currently the title for all twitter/facebook preview cards is "Life Under The Ice" and the description is "An exploratory tour through the microscopic world of Antarctica. Each microbe tells a story of the weird and whimsical life in Antarctica that is otherwise invisible to the naked eye."

How should that change when we are looking at a particular microbe, using the data from layout.json?

**Comment by ariel** [comment]
For the About and Acknowledgements page - it should say “Life Under the Ice
- PageTitle” and take the first sentence from the page.

For microbes, should be “MicrobeName - Life Under The Ice” and description
should be the first sentence from the microbe description.

**Comment by mattb** [comment]
Homepage is being wrong titled "Tardigrade - Life Under The Ice"

![image](https://user-images.githubusercontent.com/3785/72115936-90762d00-32fd-11ea-84a3-8273c4b404cc.png)
